name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion.
        Please describe your feature idea clearly.

  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: What would you like to see added or improved?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would this feature improve your workflow?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Nice to have
        - Useful improvement
        - Important
        - Critical
