name: Question
description: Ask a question about usage or configuration
title: "[Question]: "
labels: question
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Zaparoo Custom Launcher Builder?
        Fill out the details below.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Include any relevant setup details (Zaparoo version, OS, launcher type, etc.)
